### PR TITLE
Bugfix - My Applications list

### LINKED ISSUE #3: Bug - Response job applications don't appear in My Applications list
# Description
If an applicant saves and quits a Strategic Talent Response job application in progress, it does not appear under the My Applications section of their account. The applicant can return to the application via the response portal job poster.
This was likely just missed/not finished during the STR rollout as we didn't spend any time on the profile.

# Steps to Reproduce
1. Sign in as an applicant
2. Navigate to `/response`
3. Select a job
4. Begin an application
5. Save and Quit
6. Navigate to `/applications`
7. The draft does not appear under `Applications in Progress`

### PR DESCRIPTION
**Pull request by yonikid15**
Resolves #3 

### Notes:
- Since response job posters don't have a `close_date_time`, this caused the applications to fail the conditional, and not show up in the accordions. I refactored the condition to check the status of the job poster instead (`isOpen()`, `isClosed()`). 
- Split the applications list into the three accordion buckets (Application in progress, Completed Applications, Expired Applications). This removes the logic from the template into the controller.
- I removed the "Apply By" date from the application cards since response job posters do not have a close date. 
image

### CODE REVIEW

File: app/Http/Controllers/ApplicationController.php [hunk 1]
```diff
@@ -20,11 +21,34 @@ class ApplicationController extends Controller
     public function index()
     {
         $applications = Auth::user()->applicant->job_applications;
+        $applications_in_progress = [];
+        $completed_applications = [];
+        $expired_applications = [];
+
+        Log::debug($applications_in_progress);
```
Comment (tristan-orourke) [inline app/Http/Controllers/ApplicationController.php]: Oops, left in a debug log

**Review by tristan-orourke — APPROVED** [review]

File: app/Http/Controllers/ApplicationController.php (hunk 1 above)
Comment (yonikid15) [reply app/Http/Controllers/ApplicationController.php]: Thanks
